name: 'DepSafe'
description: 'Send alerts when there is unsafe updates in a pull request'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  type:
    description: 'Trigger type'
    required: true
runs:
  using: 'node16'
  main: 'binary/index.js'